# https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml -- Reference File


linters-settings:
  errcheck:
    # Report about not checking of errors in type assertions: `a := b.(MyStruct)`.
    check-type-assertions: true
   
    # Exclude Functions for err check 
    #exclude-functions:
      # This will ignore error check for tx.Rollback()  
      #- (*database/sql.Tx).Rollback
   
  staticcheck:
    # All includes all the checks available, For updating refer this document about checks: https://staticcheck.io/docs/checks/
    checks: ["all", "-SA1029"]

linters:
  disable-all: true
  enable: 
    - asciicheck
    - errcheck
    - durationcheck
    - goconst
    #- gocritic
    - gofmt
    - gosimple
    - goimports
    - gosec
    - govet
    - ineffassign
    - nilerr
    - prealloc	
    - rowserrcheck
    - staticcheck
    - sqlclosecheck
    - typecheck
    - unused

run:
  
  timeout: 3m
  
  skip-dirs: 
    - pb/*

 
